/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var http_pb = require('./http_pb.js');
var log_pb = require('./log_pb.js');
var metric_pb = require('./metric_pb.js');
var error_pb = require('./error_pb.js');
goog.exportSymbol('proto.events.Envelope', null, global);
goog.exportSymbol('proto.events.Envelope.EventType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.events.Envelope = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.events.Envelope, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.events.Envelope.displayName = 'proto.events.Envelope';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.events.Envelope.prototype.toObject = function(opt_includeInstance) {
  return proto.events.Envelope.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.events.Envelope} msg The msg instance to transform.
 * @return {!Object}
 */
proto.events.Envelope.toObject = function(includeInstance, msg) {
  var f, obj = {
    origin: jspb.Message.getField(msg, 1),
    eventtype: jspb.Message.getField(msg, 2),
    timestamp: jspb.Message.getField(msg, 6),
    deployment: jspb.Message.getField(msg, 13),
    job: jspb.Message.getField(msg, 14),
    index: jspb.Message.getField(msg, 15),
    ip: jspb.Message.getField(msg, 16),
    tagsMap: (f = msg.getTagsMap()) ? f.toArray() : [],
    httpstartstop: (f = msg.getHttpstartstop()) && http_pb.HttpStartStop.toObject(includeInstance, f),
    logmessage: (f = msg.getLogmessage()) && log_pb.LogMessage.toObject(includeInstance, f),
    valuemetric: (f = msg.getValuemetric()) && metric_pb.ValueMetric.toObject(includeInstance, f),
    counterevent: (f = msg.getCounterevent()) && metric_pb.CounterEvent.toObject(includeInstance, f),
    error: (f = msg.getError()) && error_pb.Error.toObject(includeInstance, f),
    containermetric: (f = msg.getContainermetric()) && metric_pb.ContainerMetric.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.events.Envelope}
 */
proto.events.Envelope.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.events.Envelope;
  return proto.events.Envelope.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.events.Envelope} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.events.Envelope}
 */
proto.events.Envelope.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrigin(value);
      break;
    case 2:
      var value = /** @type {!proto.events.Envelope.EventType} */ (reader.readEnum());
      msg.setEventtype(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestamp(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeployment(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setJob(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setIndex(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setIp(value);
      break;
    case 17:
      var value = msg.getTagsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString);
         });
      break;
    case 7:
      var value = new http_pb.HttpStartStop;
      reader.readMessage(value,http_pb.HttpStartStop.deserializeBinaryFromReader);
      msg.setHttpstartstop(value);
      break;
    case 8:
      var value = new log_pb.LogMessage;
      reader.readMessage(value,log_pb.LogMessage.deserializeBinaryFromReader);
      msg.setLogmessage(value);
      break;
    case 9:
      var value = new metric_pb.ValueMetric;
      reader.readMessage(value,metric_pb.ValueMetric.deserializeBinaryFromReader);
      msg.setValuemetric(value);
      break;
    case 10:
      var value = new metric_pb.CounterEvent;
      reader.readMessage(value,metric_pb.CounterEvent.deserializeBinaryFromReader);
      msg.setCounterevent(value);
      break;
    case 11:
      var value = new error_pb.Error;
      reader.readMessage(value,error_pb.Error.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 12:
      var value = new metric_pb.ContainerMetric;
      reader.readMessage(value,metric_pb.ContainerMetric.deserializeBinaryFromReader);
      msg.setContainermetric(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.events.Envelope} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.events.Envelope.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.events.Envelope.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.events.Envelope.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(this, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {!proto.events.Envelope.EventType} */ (jspb.Message.getField(this, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(this, 6));
  if (f != null) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(this, 13));
  if (f != null) {
    writer.writeString(
      13,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(this, 14));
  if (f != null) {
    writer.writeString(
      14,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(this, 15));
  if (f != null) {
    writer.writeString(
      15,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(this, 16));
  if (f != null) {
    writer.writeString(
      16,
      f
    );
  }
  f = this.getTagsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(17, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = this.getHttpstartstop();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      http_pb.HttpStartStop.serializeBinaryToWriter
    );
  }
  f = this.getLogmessage();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      log_pb.LogMessage.serializeBinaryToWriter
    );
  }
  f = this.getValuemetric();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      metric_pb.ValueMetric.serializeBinaryToWriter
    );
  }
  f = this.getCounterevent();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      metric_pb.CounterEvent.serializeBinaryToWriter
    );
  }
  f = this.getError();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      error_pb.Error.serializeBinaryToWriter
    );
  }
  f = this.getContainermetric();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      metric_pb.ContainerMetric.serializeBinaryToWriter
    );
  }
};


/**
 * required string origin = 1;
 * @return {string}
 */
proto.events.Envelope.prototype.getOrigin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.events.Envelope.prototype.setOrigin = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.events.Envelope.prototype.clearOrigin = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasOrigin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required EventType eventType = 2;
 * @return {!proto.events.Envelope.EventType}
 */
proto.events.Envelope.prototype.getEventtype = function() {
  return /** @type {!proto.events.Envelope.EventType} */ (jspb.Message.getFieldWithDefault(this, 2, 4));
};


/** @param {!proto.events.Envelope.EventType} value */
proto.events.Envelope.prototype.setEventtype = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.events.Envelope.prototype.clearEventtype = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasEventtype = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int64 timestamp = 6;
 * @return {number}
 */
proto.events.Envelope.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.events.Envelope.prototype.setTimestamp = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.events.Envelope.prototype.clearTimestamp = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string deployment = 13;
 * @return {string}
 */
proto.events.Envelope.prototype.getDeployment = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/** @param {string} value */
proto.events.Envelope.prototype.setDeployment = function(value) {
  jspb.Message.setField(this, 13, value);
};


proto.events.Envelope.prototype.clearDeployment = function() {
  jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasDeployment = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional string job = 14;
 * @return {string}
 */
proto.events.Envelope.prototype.getJob = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.events.Envelope.prototype.setJob = function(value) {
  jspb.Message.setField(this, 14, value);
};


proto.events.Envelope.prototype.clearJob = function() {
  jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasJob = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional string index = 15;
 * @return {string}
 */
proto.events.Envelope.prototype.getIndex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/** @param {string} value */
proto.events.Envelope.prototype.setIndex = function(value) {
  jspb.Message.setField(this, 15, value);
};


proto.events.Envelope.prototype.clearIndex = function() {
  jspb.Message.setField(this, 15, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasIndex = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional string ip = 16;
 * @return {string}
 */
proto.events.Envelope.prototype.getIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.events.Envelope.prototype.setIp = function(value) {
  jspb.Message.setField(this, 16, value);
};


proto.events.Envelope.prototype.clearIp = function() {
  jspb.Message.setField(this, 16, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasIp = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * map<string, string> tags = 17;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.events.Envelope.prototype.getTagsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 17, opt_noLazyCreate,
      null));
};


proto.events.Envelope.prototype.clearTagsMap = function() {
  this.getTagsMap().clear();
};


/**
 * optional HttpStartStop httpStartStop = 7;
 * @return {?proto.events.HttpStartStop}
 */
proto.events.Envelope.prototype.getHttpstartstop = function() {
  return /** @type{?proto.events.HttpStartStop} */ (
    jspb.Message.getWrapperField(this, http_pb.HttpStartStop, 7));
};


/** @param {?proto.events.HttpStartStop|undefined} value */
proto.events.Envelope.prototype.setHttpstartstop = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.events.Envelope.prototype.clearHttpstartstop = function() {
  this.setHttpstartstop(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasHttpstartstop = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional LogMessage logMessage = 8;
 * @return {?proto.events.LogMessage}
 */
proto.events.Envelope.prototype.getLogmessage = function() {
  return /** @type{?proto.events.LogMessage} */ (
    jspb.Message.getWrapperField(this, log_pb.LogMessage, 8));
};


/** @param {?proto.events.LogMessage|undefined} value */
proto.events.Envelope.prototype.setLogmessage = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.events.Envelope.prototype.clearLogmessage = function() {
  this.setLogmessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasLogmessage = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional ValueMetric valueMetric = 9;
 * @return {?proto.events.ValueMetric}
 */
proto.events.Envelope.prototype.getValuemetric = function() {
  return /** @type{?proto.events.ValueMetric} */ (
    jspb.Message.getWrapperField(this, metric_pb.ValueMetric, 9));
};


/** @param {?proto.events.ValueMetric|undefined} value */
proto.events.Envelope.prototype.setValuemetric = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


proto.events.Envelope.prototype.clearValuemetric = function() {
  this.setValuemetric(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasValuemetric = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional CounterEvent counterEvent = 10;
 * @return {?proto.events.CounterEvent}
 */
proto.events.Envelope.prototype.getCounterevent = function() {
  return /** @type{?proto.events.CounterEvent} */ (
    jspb.Message.getWrapperField(this, metric_pb.CounterEvent, 10));
};


/** @param {?proto.events.CounterEvent|undefined} value */
proto.events.Envelope.prototype.setCounterevent = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


proto.events.Envelope.prototype.clearCounterevent = function() {
  this.setCounterevent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasCounterevent = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional Error error = 11;
 * @return {?proto.events.Error}
 */
proto.events.Envelope.prototype.getError = function() {
  return /** @type{?proto.events.Error} */ (
    jspb.Message.getWrapperField(this, error_pb.Error, 11));
};


/** @param {?proto.events.Error|undefined} value */
proto.events.Envelope.prototype.setError = function(value) {
  jspb.Message.setWrapperField(this, 11, value);
};


proto.events.Envelope.prototype.clearError = function() {
  this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasError = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional ContainerMetric containerMetric = 12;
 * @return {?proto.events.ContainerMetric}
 */
proto.events.Envelope.prototype.getContainermetric = function() {
  return /** @type{?proto.events.ContainerMetric} */ (
    jspb.Message.getWrapperField(this, metric_pb.ContainerMetric, 12));
};


/** @param {?proto.events.ContainerMetric|undefined} value */
proto.events.Envelope.prototype.setContainermetric = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.events.Envelope.prototype.clearContainermetric = function() {
  this.setContainermetric(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.Envelope.prototype.hasContainermetric = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * @enum {number}
 */
proto.events.Envelope.EventType = {
  HTTPSTARTSTOP: 4,
  LOGMESSAGE: 5,
  VALUEMETRIC: 6,
  COUNTEREVENT: 7,
  ERROR: 8,
  CONTAINERMETRIC: 9
};

goog.object.extend(exports, proto.events);
