/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var uuid_pb = require('./uuid_pb.js');
goog.exportSymbol('proto.events.HttpStartStop', null, global);
goog.exportSymbol('proto.events.Method', null, global);
goog.exportSymbol('proto.events.PeerType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.events.HttpStartStop = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.events.HttpStartStop.repeatedFields_, null);
};
goog.inherits(proto.events.HttpStartStop, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.events.HttpStartStop.displayName = 'proto.events.HttpStartStop';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.events.HttpStartStop.repeatedFields_ = [15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.events.HttpStartStop.prototype.toObject = function(opt_includeInstance) {
  return proto.events.HttpStartStop.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.events.HttpStartStop} msg The msg instance to transform.
 * @return {!Object}
 */
proto.events.HttpStartStop.toObject = function(includeInstance, msg) {
  var f, obj = {
    starttimestamp: jspb.Message.getField(msg, 1),
    stoptimestamp: jspb.Message.getField(msg, 2),
    requestid: (f = msg.getRequestid()) && uuid_pb.UUID.toObject(includeInstance, f),
    peertype: jspb.Message.getField(msg, 4),
    method: jspb.Message.getField(msg, 5),
    uri: jspb.Message.getField(msg, 6),
    remoteaddress: jspb.Message.getField(msg, 7),
    useragent: jspb.Message.getField(msg, 8),
    statuscode: jspb.Message.getField(msg, 9),
    contentlength: jspb.Message.getField(msg, 10),
    applicationid: (f = msg.getApplicationid()) && uuid_pb.UUID.toObject(includeInstance, f),
    instanceindex: jspb.Message.getField(msg, 13),
    instanceid: jspb.Message.getField(msg, 14),
    forwardedList: jspb.Message.getField(msg, 15)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.events.HttpStartStop}
 */
proto.events.HttpStartStop.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.events.HttpStartStop;
  return proto.events.HttpStartStop.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.events.HttpStartStop} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.events.HttpStartStop}
 */
proto.events.HttpStartStop.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStarttimestamp(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStoptimestamp(value);
      break;
    case 3:
      var value = new uuid_pb.UUID;
      reader.readMessage(value,uuid_pb.UUID.deserializeBinaryFromReader);
      msg.setRequestid(value);
      break;
    case 4:
      var value = /** @type {!proto.events.PeerType} */ (reader.readEnum());
      msg.setPeertype(value);
      break;
    case 5:
      var value = /** @type {!proto.events.Method} */ (reader.readEnum());
      msg.setMethod(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setUri(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setRemoteaddress(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setUseragent(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStatuscode(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setContentlength(value);
      break;
    case 12:
      var value = new uuid_pb.UUID;
      reader.readMessage(value,uuid_pb.UUID.deserializeBinaryFromReader);
      msg.setApplicationid(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInstanceindex(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstanceid(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.addForwarded(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.events.HttpStartStop} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.events.HttpStartStop.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.events.HttpStartStop.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.events.HttpStartStop.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(this, 1));
  if (f != null) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(this, 2));
  if (f != null) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = this.getRequestid();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      uuid_pb.UUID.serializeBinaryToWriter
    );
  }
  f = /** @type {!proto.events.PeerType} */ (jspb.Message.getField(this, 4));
  if (f != null) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = /** @type {!proto.events.Method} */ (jspb.Message.getField(this, 5));
  if (f != null) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(this, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(this, 7));
  if (f != null) {
    writer.writeString(
      7,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(this, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(this, 9));
  if (f != null) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(this, 10));
  if (f != null) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = this.getApplicationid();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      uuid_pb.UUID.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(this, 13));
  if (f != null) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(this, 14));
  if (f != null) {
    writer.writeString(
      14,
      f
    );
  }
  f = this.getForwardedList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      15,
      f
    );
  }
};


/**
 * required int64 startTimestamp = 1;
 * @return {number}
 */
proto.events.HttpStartStop.prototype.getStarttimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.events.HttpStartStop.prototype.setStarttimestamp = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.events.HttpStartStop.prototype.clearStarttimestamp = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasStarttimestamp = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int64 stopTimestamp = 2;
 * @return {number}
 */
proto.events.HttpStartStop.prototype.getStoptimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.events.HttpStartStop.prototype.setStoptimestamp = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.events.HttpStartStop.prototype.clearStoptimestamp = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasStoptimestamp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required UUID requestId = 3;
 * @return {!proto.events.UUID}
 */
proto.events.HttpStartStop.prototype.getRequestid = function() {
  return /** @type{!proto.events.UUID} */ (
    jspb.Message.getWrapperField(this, uuid_pb.UUID, 3, 1));
};


/** @param {!proto.events.UUID} value */
proto.events.HttpStartStop.prototype.setRequestid = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.events.HttpStartStop.prototype.clearRequestid = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasRequestid = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required PeerType peerType = 4;
 * @return {!proto.events.PeerType}
 */
proto.events.HttpStartStop.prototype.getPeertype = function() {
  return /** @type {!proto.events.PeerType} */ (jspb.Message.getFieldWithDefault(this, 4, 1));
};


/** @param {!proto.events.PeerType} value */
proto.events.HttpStartStop.prototype.setPeertype = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.events.HttpStartStop.prototype.clearPeertype = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasPeertype = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * required Method method = 5;
 * @return {!proto.events.Method}
 */
proto.events.HttpStartStop.prototype.getMethod = function() {
  return /** @type {!proto.events.Method} */ (jspb.Message.getFieldWithDefault(this, 5, 1));
};


/** @param {!proto.events.Method} value */
proto.events.HttpStartStop.prototype.setMethod = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.events.HttpStartStop.prototype.clearMethod = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasMethod = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * required string uri = 6;
 * @return {string}
 */
proto.events.HttpStartStop.prototype.getUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.events.HttpStartStop.prototype.setUri = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.events.HttpStartStop.prototype.clearUri = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasUri = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * required string remoteAddress = 7;
 * @return {string}
 */
proto.events.HttpStartStop.prototype.getRemoteaddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.events.HttpStartStop.prototype.setRemoteaddress = function(value) {
  jspb.Message.setField(this, 7, value);
};


proto.events.HttpStartStop.prototype.clearRemoteaddress = function() {
  jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasRemoteaddress = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * required string userAgent = 8;
 * @return {string}
 */
proto.events.HttpStartStop.prototype.getUseragent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.events.HttpStartStop.prototype.setUseragent = function(value) {
  jspb.Message.setField(this, 8, value);
};


proto.events.HttpStartStop.prototype.clearUseragent = function() {
  jspb.Message.setField(this, 8, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasUseragent = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * required int32 statusCode = 9;
 * @return {number}
 */
proto.events.HttpStartStop.prototype.getStatuscode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.events.HttpStartStop.prototype.setStatuscode = function(value) {
  jspb.Message.setField(this, 9, value);
};


proto.events.HttpStartStop.prototype.clearStatuscode = function() {
  jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasStatuscode = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * required int64 contentLength = 10;
 * @return {number}
 */
proto.events.HttpStartStop.prototype.getContentlength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.events.HttpStartStop.prototype.setContentlength = function(value) {
  jspb.Message.setField(this, 10, value);
};


proto.events.HttpStartStop.prototype.clearContentlength = function() {
  jspb.Message.setField(this, 10, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasContentlength = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional UUID applicationId = 12;
 * @return {?proto.events.UUID}
 */
proto.events.HttpStartStop.prototype.getApplicationid = function() {
  return /** @type{?proto.events.UUID} */ (
    jspb.Message.getWrapperField(this, uuid_pb.UUID, 12));
};


/** @param {?proto.events.UUID|undefined} value */
proto.events.HttpStartStop.prototype.setApplicationid = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.events.HttpStartStop.prototype.clearApplicationid = function() {
  this.setApplicationid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasApplicationid = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional int32 instanceIndex = 13;
 * @return {number}
 */
proto.events.HttpStartStop.prototype.getInstanceindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {number} value */
proto.events.HttpStartStop.prototype.setInstanceindex = function(value) {
  jspb.Message.setField(this, 13, value);
};


proto.events.HttpStartStop.prototype.clearInstanceindex = function() {
  jspb.Message.setField(this, 13, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasInstanceindex = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional string instanceId = 14;
 * @return {string}
 */
proto.events.HttpStartStop.prototype.getInstanceid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.events.HttpStartStop.prototype.setInstanceid = function(value) {
  jspb.Message.setField(this, 14, value);
};


proto.events.HttpStartStop.prototype.clearInstanceid = function() {
  jspb.Message.setField(this, 14, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.events.HttpStartStop.prototype.hasInstanceid = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * repeated string forwarded = 15;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<string>}
 */
proto.events.HttpStartStop.prototype.getForwardedList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getField(this, 15));
};


/** @param {!Array.<string>} value */
proto.events.HttpStartStop.prototype.setForwardedList = function(value) {
  jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.events.HttpStartStop.prototype.addForwarded = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


proto.events.HttpStartStop.prototype.clearForwardedList = function() {
  this.setForwardedList([]);
};


/**
 * @enum {number}
 */
proto.events.PeerType = {
  CLIENT: 1,
  SERVER: 2
};

/**
 * @enum {number}
 */
proto.events.Method = {
  GET: 1,
  POST: 2,
  PUT: 3,
  DELETE: 4,
  HEAD: 5,
  ACL: 6,
  BASELINE_CONTROL: 7,
  BIND: 8,
  CHECKIN: 9,
  CHECKOUT: 10,
  CONNECT: 11,
  COPY: 12,
  DEBUG: 13,
  LABEL: 14,
  LINK: 15,
  LOCK: 16,
  MERGE: 17,
  MKACTIVITY: 18,
  MKCALENDAR: 19,
  MKCOL: 20,
  MKREDIRECTREF: 21,
  MKWORKSPACE: 22,
  MOVE: 23,
  OPTIONS: 24,
  ORDERPATCH: 25,
  PATCH: 26,
  PRI: 27,
  PROPFIND: 28,
  PROPPATCH: 29,
  REBIND: 30,
  REPORT: 31,
  SEARCH: 32,
  SHOWMETHOD: 33,
  SPACEJUMP: 34,
  TEXTSEARCH: 35,
  TRACE: 36,
  TRACK: 37,
  UNBIND: 38,
  UNCHECKOUT: 39,
  UNLINK: 40,
  UNLOCK: 41,
  UPDATE: 42,
  UPDATEREDIRECTREF: 43,
  VERSION_CONTROL: 44
};

goog.object.extend(exports, proto.events);
